### ISSUE TITLE
Markdown renderer treats incorrect link markdown badly

### ISSUE THREAD

**Issue by fofr** [DFE-Digital/search-and-compare-ui#114]
This markdown:
![screen shot 2018-09-17 at 12 11 15](https://user-images.githubusercontent.com/319055/45619934-fab4ef80-ba72-11e8-9e13-eeb35830d919.png)

Becomes:
![screen shot 2018-09-17 at 12 10 36](https://user-images.githubusercontent.com/319055/45619938-fe487680-ba72-11e8-853d-4cd22848dd66.png)

Where the link points to: `/organisation/…/course/self/…/Please%20click`

Standard markdown would do this (eg Github's):

Overseas applicants will need a NARIC equivalency certificate. [Please click] (https://www.naric.org.uk/naric/)  for further information.

See also https://github.com/DFE-Digital/manage-courses-ui/issues/188 (the problem is the space between the brackets)

**Comment by tvararu** [comment]
Fixed in https://github.com/DFE-Digital/search-and-compare-ui/pull/166.
