### ISSUE TITLE
Link in error message doesn't work (Find by location)

### ISSUE THREAD

**Issue by fofr** [DFE-Digital/search-and-compare-ui#298]
Clicking "please choose an option" doesn't do anything.

![screen shot 2018-11-29 at 09 52 22](https://user-images.githubusercontent.com/319055/49213610-94c2dd80-f3bc-11e8-889a-3e2c53a85adc.png)

**Comment by fofr** [comment]
@pgenders Probably could have better words too.

**Comment by dankmitchell** [comment]
@fofr this link does navigate to the correct place on the page but I assume you were using a large screen so there no scroll..

**Comment by fofr** [comment]
Behaviour is confusing on big screens.
