### ISSUE TITLE
Javascript back link breaks if users use contents list

### ISSUE THREAD

**Issue by fofr** [DFE-Digital/search-and-compare-ui#90]
The back link is inserted by JS if there's a referrer. It uses `history.back()`.

If a user clicks the contents list, eg #section-about, then another history entry is added to the stack. So "Back to results" or "Back to course" in preview mode, will point to #section-about rather than the previous page.

**Comment by tvararu** [comment]
Fixed by https://github.com/DFE-Digital/search-and-compare-ui/pull/235.
