### ISSUE TITLE
Change financial support text on salaried courses

### ISSUE THREAD

**Issue by fofr** [DFE-Digital/search-and-compare-ui#99]
For a salaried course, financial support should say:

## Financial support

Financial support isn’t available for this course.

If you choose a course without a salary, you may be eligible for financial support while you study, including bursaries, scholarships and loans.

(see https://becomingateacher.zendesk.com/agent/tickets/321)

**Comment by dankmitchell** [comment]
@fofr should this content only show for salaried courses?

**Comment by fofr** [comment]
@dankmitchell:
> For a salaried course
